# Generated by Django 5.0.6 on 2024-07-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='cityname',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='State',
            new_name='state',
        ),
    ]
